import './globals.css';
import 'slick-carousel/slick/slick.css';
import 'slick-carousel/slick/slick-theme.css';

import { Open_Sans, Kanit } from 'next/font/google';
import type { Metadata } from 'next';
import { clsx } from 'clsx';
import Header from '@/components/Header';
import Providers from '@/components/context/providers';
import { Toaster } from '@/components/ui/toaster';
import { TailwindIndicator } from '@/components/TailwindIndicator';
import { Footer } from '@/components/Footer';

const sans = Open_Sans({
  weight: ['400', '600', '700', '800'],
  variable: '--font-sans',
  display: 'swap',
  subsets: ['latin'],
});

const kanit = Kanit({
  weight: ['200', '300', '400', '600', '700', '800'],
  variable: '--font-kanit',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: {
    default: 'Room Match',
    template: '%s | Room Match',
  },
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={clsx(sans.variable, kanit.variable, 'font-sans')}
      suppressHydrationWarning
    >
      <body className={'antialiased'} suppressHydrationWarning>
        <Providers>
          <Header />
          {children}
          <Footer />
          <TailwindIndicator />
        </Providers>
        <Toaster />
      </body>
    </html>
  );
}
